name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Aliyun FC 2
        run: |
          sudo apt-get install python3-setuptools
          sudo pip3 install -U aliyun-fc2 pip

      - name: Deploy with Aliyun FC 2
        env:
          FUNCTION_COMPUTE_ARN: ${{ secrets.FUNCTION_COMPUTE_ARN }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          pip3 install -t dist pandas==1.4.2
          rm -rf dist/numpy*
          cp -r src/* dist/
          ./setup.py deploy
