name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Aliyun FC 2
        run: |
          sudo apt-get install python3-setuptools
          sudo pip3 install aliyun-fc2

      - name: Deploy with Aliyun FC 2
        env:
          FUNCTION_COMPUTE_ARN: ${{ secrets.FUNCTION_COMPUTE_ARN }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          pip3 install --system -t dist pandas==1.0.5
          rm -rf dist/numpy*
          cp -r src/* dist/
          python3 setup.py deploy
